# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [115]:
import torch

In [116]:
print(torch.__version__)

2.6.0+cu124


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
ten = torch.tensor([i for i in range(10)])
ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [118]:
print(ten.dtype, "- тип элементов")
print(ten.shape, "- размер")
print(ten.dim(), "- количество размерностей")

torch.int64 - тип элементов
torch.Size([10]) - размер
1 - количество размерностей


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [119]:
ten_left = ten[:5]
print(ten_left)
ten_right = ten[5:]
print(ten_right)

tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [120]:
r_arr = [[1 for i in range(4)] for j in range(3)]
r_arr

[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]

Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [121]:
r_arr = [[True for i in range(2)] for j in range(5)]
r_arr

[[True, True], [True, True], [True, True], [True, True], [True, True]]

Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [122]:
torch.tensor([i / 2 for i in range(2, 31, 1)])

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000])

Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [123]:
torch.linspace(1, 10, 20, dtype=torch.float64)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000], dtype=torch.float64)

Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [124]:
torch.rand(4, 3)

tensor([[0.3582, 0.8403, 0.1082],
        [0.7223, 0.6639, 0.4991],
        [0.7469, 0.8772, 0.2727],
        [0.6962, 0.0571, 0.9624]])

Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [125]:
ten_sch = torch.randint(3, 6, (100,))
ten_sch

tensor([5, 3, 5, 5, 4, 5, 5, 5, 4, 4, 3, 3, 3, 3, 4, 4, 5, 4, 4, 5, 4, 3, 3, 3,
        4, 4, 3, 4, 3, 5, 3, 3, 4, 4, 4, 4, 4, 3, 3, 3, 4, 5, 4, 4, 4, 5, 5, 3,
        3, 4, 5, 5, 4, 5, 5, 5, 3, 3, 4, 4, 3, 3, 5, 4, 4, 5, 4, 4, 3, 5, 5, 3,
        5, 3, 5, 5, 5, 4, 3, 3, 3, 3, 4, 4, 3, 4, 4, 3, 5, 5, 4, 4, 3, 3, 5, 5,
        5, 3, 4, 3])

Задание 11. Для тензора "школьных отенок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [126]:
print('Минимум -', ten_sch.min())
print('Максимум -', ten_sch.max())
print('Среднее -', ten_sch.float().mean())

Минимум - tensor(3)
Максимум - tensor(5)
Среднее - tensor(3.9600)


Задание 12. Создайте создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [127]:
bool_mask = torch.tensor([True for i in range(5)] + [False for i in range(90)] + [True for i in range(5)])

Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [128]:
ten_sch[bool_mask]

tensor([5, 3, 5, 5, 4, 5, 5, 3, 4, 3])

Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [129]:
bool_mask_1 = [True if i == 5 else False for i in ten_sch]

Задание 15. Извлеките все "пятерки" из тензора "школьных оценок", созданного в задании 10, и занесите их в новый тензор.


In [130]:
new_ten_sch = ten_sch[bool_mask_1]

Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [73]:
torch.tensor([[ten_sch[i * 20 + j].item() for j in range(20)] for i in range(5)])
#Или
ten_sch.reshape(5, 20)

tensor([[3, 5, 5, 5, 3, 3, 3, 4, 4, 4, 3, 5, 3, 3, 5, 3, 4, 4, 3, 3],
        [3, 5, 5, 3, 4, 3, 3, 5, 4, 5, 5, 4, 4, 3, 5, 5, 5, 4, 4, 5],
        [3, 4, 3, 5, 4, 3, 4, 5, 4, 4, 3, 3, 5, 4, 5, 3, 3, 4, 4, 4],
        [4, 5, 4, 5, 3, 5, 5, 3, 4, 3, 4, 5, 4, 3, 4, 4, 5, 4, 5, 4],
        [5, 4, 3, 5, 4, 4, 4, 5, 3, 3, 5, 4, 4, 3, 4, 4, 3, 4, 5, 3]])

Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.tensor([1] * 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [85]:
vert = torch.cat([torch.cat([torch.arange(2, 10, 2).reshape(2, -1), torch.zeros(2, 3)], dim=1), torch.tensor([1] * 10).reshape(2, -1)], dim=0).int()
vert

tensor([[2, 4, 0, 0, 0],
        [6, 8, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.tensor([1] * 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [106]:
gor = torch.cat([torch.cat([torch.arange(2, 10, 2).reshape(2, -1), torch.zeros(2, 3)], dim=1), torch.tensor([1] * 10).reshape(2, -1)], dim=1).int()
gor

tensor([[2, 4, 0, 0, 0, 1, 1, 1, 1, 1],
        [6, 8, 0, 0, 0, 1, 1, 1, 1, 1]], dtype=torch.int32)

Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [107]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
torch.tensor([i for i in a if 5 <= i <= 10])

tensor([ 6,  9, 10])

Задание 20. Вывести первую строку матрицы из задания 18.

In [108]:
gor[0]

tensor([2, 4, 0, 0, 0, 1, 1, 1, 1, 1], dtype=torch.int32)

Задание 21. Вывести последний столбец матрицы из задания 17.

In [109]:
torch.tensor([vert[i][-1] for i in range(len(vert))])

tensor([0, 0, 1, 1], dtype=torch.int32)

Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [110]:
vert[1:3, 1:4]

tensor([[8, 0, 0],
        [1, 1, 1]], dtype=torch.int32)

Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [111]:
min_value = vert.min()
new_row = torch.full((1, 5), min_value)
new_vert = torch.cat([new_row, vert], dim=0)

Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [112]:
for i in range(len(new_vert)):
    for j in range(len(new_vert[i])):
        new_vert[i][j] = new_vert[i][j] * new_vert[i][j]
new_vert        

tensor([[ 0,  0,  0,  0,  0],
        [ 4, 16,  0,  0,  0],
        [36, 64,  0,  0,  0],
        [ 1,  1,  1,  1,  1],
        [ 1,  1,  1,  1,  1]])

Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [114]:
for i in range(len(gor)):
    for j in range(len(gor[i])):
        if gor[i][j] % 2 == 0 or gor[i][j] % 3 == 0:
            gor[i][j] = 1
gor            

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.int32)